language: java
jdk:
    - openjdk7
    - openjdk8
before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-openjdk-amd64
    - export JAVA8_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - export JAVA_HOME=$JAVA8_HOME
script:
    - ./gradlew clean assemble check
